Add fn<->win key inverter
BeardOverflow/msi-ec pull request #132
Opened 2024-06-10 18:20 UTC by TGODiamond

Adds a new field in `msi_ec_fn_win_swap_conf`, a bool named `invert`. Set to true if the fn<->win config files report the opposite direction.

2024-06-11 14:39 UTC, TGODiamond commented
PR is ready to be merged! :)

2024-06-11 15:26 UTC, TGODiamond commented
There we go! Ready, for real this time!

2024-06-11 18:40 UTC, teackot commented
Hi! Thanks for the PR

I'm thinking we can make the code more readable by merging the `ec_set_bit()` and `ec_unset_bit()` into a single `ec_set_bit(u8 addr, u8 bit, bool value)` function, which just choses between the set_bit and unset_bit macros. This way we can avoid both the nested ifs (in your first version) and very long lines with ternaries (they don't like long lines in the kernel). It'll also simplify the `[mic]mute_led_sysfs_set()` functions

2024-06-11 20:14 UTC, glpnk commented
We can make EC_RS_BIT(addr, bit, val) and EC_RS_BITS(addr, bit(?), size(?), val), which should write single bit and several bits

2024-06-11 20:56 UTC, teackot commented
Doesn't seem like we win anything by doing this. The performance impact of different bit manipulation algos is negligible as the functions are called very rarely. So I think we should prioritize readability and keep bit manipulations simple

2024-06-11 21:15 UTC, glpnk commented
Other kernel modules might share own bit manipulation algo, so we can use it

2024-06-11 22:03 UTC, teackot commented
I looked for examples similar to mine. None of them use dedicated (un)set_bit macros, but they use an `if`

[one](https://github.com/torvalds/linux/blob/83a7eefedc9b56fe7bfeff13b6c7356688ffa670/drivers/platform/x86/intel/pmc/core.c#L578), and basically the same: [two](https://github.com/torvalds/linux/blob/83a7eefedc9b56fe7bfeff13b6c7356688ffa670/drivers/platform/x86/intel/pmt/crashlog.c#L104)

```c
if (reset)
	fd &= ~CNP_PMC_LATCH_SLPS0_EVENTS;
else
	fd |= CNP_PMC_LATCH_SLPS0_EVENTS;
```

A little different, but also manipulates EC: [three](https://github.com/torvalds/linux/blob/83a7eefedc9b56fe7bfeff13b6c7356688ffa670/drivers/platform/x86/eeepc-laptop.c#L1004)

```c
static void eeepc_set_fan_ctrl(int manual)
{
	u8 value = 0;

	ec_read(EEEPC_EC_FAN_CTRL, &value);
	if (manual == EEEPC_FAN_CTRL_MANUAL)
		value |= EEEPC_EC_FAN_CTRL_BIT;
	else
		value &= ~EEEPC_EC_FAN_CTRL_BIT;
	ec_write(EEEPC_EC_FAN_CTRL, value);
}
```

2024-06-12 14:35 UTC, TGODiamond commented
> I'm thinking we can make the code more readable by merging the ec_set_bit() and ec_unset_bit() into a single ec_set_bit(u8 addr, u8 bit, bool value) function

Did just that, looks much better now!

2024-06-12 16:51 UTC, teackot commented
Great! Just some Kernel-specific style remarks and we can merge it

2024-06-12 17:00 UTC, teackot requested changes

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +	}
```suggestion
	if (value)
		set_bit(stored, bit);
	else
		unset_bit(stored, bit);
```

No braces required here

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					true ^ conf.fn_win_swap.invert);
```suggestion
		result = ec_set_bit(conf.fn_win_swap.address,
				    conf.fn_win_swap.bit,
				    true ^ conf.fn_win_swap.invert);
```

Alignment

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					false ^ conf.fn_win_swap.invert);
```suggestion
		result = ec_set_bit(conf.fn_win_swap.address,
				    conf.fn_win_swap.bit,
				    false ^ conf.fn_win_swap.invert);
```

Alignment

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					false ^ conf.fn_win_swap.invert);
```suggestion
		result = ec_set_bit(conf.fn_win_swap.address,
				    conf.fn_win_swap.bit,
				    false ^ conf.fn_win_swap.invert);
```

More alignment

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					true ^ conf.fn_win_swap.invert);
```suggestion
		result = ec_set_bit(conf.fn_win_swap.address,
				    conf.fn_win_swap.bit, 
				    true ^ conf.fn_win_swap.invert);
```

Ditto

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					true);
```suggestion
				    conf.cooler_boost.bit,
				    true);
```

2024-06-12 17:00 UTC, teackot commented on msi-ec.c
> +					false);
```suggestion
		result = ec_set_bit(conf.cooler_boost.address,
				    conf.cooler_boost.bit,
				    false);
```

2024-06-12 17:27 UTC, TGODiamond commented
There you go!

2024-06-12 17:31 UTC, TGODiamond commented
Is it really correct formatting? We are mixing tabs and spaces now.

2024-06-12 18:20 UTC, teackot commented
Yes, tabs + spaces are allowed to be used for alignment, only tabs can be used for indentation

Thanks! Merging now

2024-06-12 18:21 UTC, merged